### ISSUE TITLE
covarianceMatrix errors

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#100]
`
D=digraph{{1,6},{4,7}}
R4=gaussianRing D
covarianceMatrix R4

stdio:66:1:(3): error: key not found in hash table
`
works fine if instead use mixedGraph D. also works if it's a gaussian ring of a Bigraph or a Graph.

**Comment by roserhp** [comment]
Two things go wrong for Digraphs:

1. I forgot to add R.gaussianRingData#svar, sorry. 
2. I just realized that R.gaussianVariables has a different format for gaussianRing digraphs. This is another reason to do step 1 in #98. I haven't changed that because that will imply changing gaussianVanishingIdeals so I want to wait for what Carlos and Luis think about that.

I'll fix this right after our meeting in the afternoon.

**Comment by roserhp** [comment]
solved
