### ISSUE TITLE
gaussianRings - add option without checks

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#121]
I suggest we add an optional argument "runChecks" that allows to turn off checks as it was before and by default it is false.
Otherwise, this example https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.16/share/doc/Macaulay2/GraphicalModels/html/_identify__Parameters.html will never run as it clearly contains a directed cycle.

Perhaps, if we allow checks, then we can also specify the type of checks, and this is where we can add back the check for multiple edges that you created.

What do you think?

**Comment by roserhp** [comment]
I think that one option that will ensure that no test example from previous versions breaks is to add an "if" in the construction of the gaussianRing of the mixedGraph such that whenever our mixedGraph has no undirected edges, it avoids all checks. In such case we can take the partition U and W such that W=V and U is empty. All checks would only appear when we have undirected edges, i.e. when actually need partitionLMG (when we need a proper partition). This won't lead to conflicts because such kind of mixed graphs were not allowed in previous versions. I don't think it's a good idea to get rid of the checks in this last case because we need them to construct the partition.

**Comment by olgakuznetsova** [comment]
Ok. I think in this case we should still check that the sub graphs are simple, but can skip the directed cycle check.

**Comment by roserhp** [comment]
The actual state of gaussianRing mixedGraph is that the checks only apply if there are undirected edges in the mixedGraph. Let's discuss today exactly which checks should be done or should be optional for such mixedGraphs.

**Comment by luisgarciapuente** [comment]
Is the following link still the correct zoom meeting? 

https://aalto.zoom.us/j/65054720331 <https://aalto.zoom.us/j/65054720331>

Luis

**Comment by roserhp** [comment]
Check #166
