### ISSUE TITLE
Warnings in partitionLMG

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#154]
@roserhp we have probably discussed this but now I forgot, sorry: why are these warnings and not errors?

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/efa4e5df2c544d671f85c2ee144b26a254c12491/AlgebraicStatistics/MLE/StatGraphs.m2#L266

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/efa4e5df2c544d671f85c2ee144b26a254c12491/AlgebraicStatistics/MLE/StatGraphs.m2#L272

**Comment by roserhp** [comment]
We need this restrictions for the computation of the MLE but the partition is already computed in the gaussianRing itself because we need it to create the matrices K,L,P. So it seemed that it was too restrictive to not allow this in the ring itself.

I must say that I am super confused about all this. I can't find in Lauritzen reference (the mixed graph paper) where the 
partition Carlos wrote in our background document comes from.

This is highly connected to https://github.com/Macaulay2/Workshop-2020-Warwick/issues/149 because to document the kind
of gaussianRings mixedGraphs we are building we need a good understanding of how restrictive is this partition. Plus I think we should say something in the intro of GraphicalModelsMLE about exactly for which king of graphs we are giving a meaningful MLE.

**Comment by olgakuznetsova** [comment]
Hi @roserhp @lukeamendola 
Did you have a chance to discuss this yesterday?

**Comment by roserhp** [comment]
No, we could only discuss solverMLE. Let's do it on Thursday!

**Comment by roserhp** [comment]
Check #166
