### ISSUE TITLE
How can we access gaussianRingData or gaussianRingList?

### ISSUE THREAD

**Issue by roserhp** [Macaulay2/Workshop-2020-Warwick#50]
In many parts of code of GraphicalModels.m2, M2 retrieves info of the ring by using R.gaussianRingData#something like in
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/0effb01eaec03bbd407781a5c79c631814395789/AlgebraicStatistics/MLE/GraphicalModels.m2#L691
but I can't do by myself:
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/0effb01eaec03bbd407781a5c79c631814395789/AlgebraicStatistics/MLE/TESTS_GaussianRingMixedGraphs.m2#L23

How can I access this information?

**Comment by haerski** [comment]
`gaussianRingData` is a local symbol in `GraphicalModels`, so it can't be easily accessible from outside the package itself. Just note that usually if package authors define symbols locally, it is because they don't want to users to mess with them (e.g. things may break unexpectedly). If you're sure about what you're doing, there are a couple ways to access these symbols. One way is to run `debug GraphicalModels` after loading the package. This will give you access to all local symbols in the package:
```macaulay2
debug needsPackage "GraphicalModels"
R = gaussianRing 4
R.gaussianRingData
```
This is useful for your own tests, but is probably not appropriate in released code. A "safer" way would be to look in the private dictionnary of the package. For example
```macaulay2
needsPackage "GraphicalModels"
R = gaussianRing 4
R#(GraphicalModels#"private dictionary"#"gaussianRingData")
```
