### ISSUE TITLE
scoreEquations for a mixedGraph with only undirected edges doesn't finish computations

### ISSUE THREAD

**Issue by roserhp** [Macaulay2/Workshop-2020-Warwick#67]
scoreEquations for a mixedGraph with only undirected edges doesn't finish computations whereas scoreEquationsFromCovarianceaMatrixUndir gives result straight away. Even without saturation doesn't finish. The bottleneck seems to be the product of the denominators...

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/7a4e8bc28005f54634fbc962a68c025136116b3e/AlgebraicStatistics/MLE/TestsForGMMLERoser.m2#L124-L128

**Comment by olgakuznetsova** [comment]
That's annoying :( I'll look at it tomorrow

Did I understand correctly that all examples above line 124 ran properly?

**Comment by roserhp** [comment]
Yes, everything else ran properly. It can be easily rechecked because I saved the ideals computed by scoreEquationsFromCovarianceMatrixUndir in order to compare them with what we get with scoreEquationsFromCovarianceMatrix. 

With that particular example the core computation of the score equations ideal (where LL is computed) already takes several minutes. The difference with the code of the undirected case is basically that on the latter we compute det(K) and its jacobian whereas for mixedGraphs we compute det(K^(-1)) and its jacobian. But in any case this step would just slow the computation a few minutes. I have no idea why the product of denominators is such a big issue. A weird thing is that if I run the code line by line, I get an error in this line (you can see the error message it in TestsFroGMMLERoser). However, if I execute scoreEquationsFromCovarianceMatrix (without saturation) it doesn't finish but it doesn't output an error either...

Maybe we should add an if for the degenerate case where only undirected edges are present... it makes no sense to slow down computations if we have a faster way.

**Comment by olgakuznetsova** [comment]
ok, I think I understand the problem. When you build up S from all those submatrices, the resulting matrix looks super complicated even if its inverse can be simplified to K. I tried to bypass that by introducing if statements for the degenerate cases in https://github.com/Macaulay2/Workshop-2020-Warwick/blob/40596813ebf187c7bc2d5bb1c04479fff9340bb6/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L221-L233 but that's clearly not sufficient
I think there are a couple of ways:
1. Somehow check whether S or S^{-1} are simpler and then work with the best option (though not sure how to define "simpler")
2. Check whether there are more vertices in U or W and then work with S or S^{-1} 
3. Perhaps best, is to rewrite the code so that it operates on K and Psi separately and then reconstructs Sigma from the block matrices.
I think I'll start working on option 3 now. What do you think?

**Comment by olgakuznetsova** [comment]
Ok, option 3 is not that good actually (so let's discuss tomorrow). But in that example, Kinv takes 400 lines to print, so this explains why taking the Jacobean of its determinant is not realistic

**Comment by olgakuznetsova** [comment]
In our formula we take inverses twice:
1. K^{-1}
2. (I-Lambda)^{-1}
and to make things worse, we also multiply matrices, so what started as sth sparse  or at least with a nice block structure is not necessarily sparse or nice in the end.

So the computations will start failing very quickly even in the simplest examples. I think our best shot with reasonable effort is to keep the function as is, but also publish the one for undirected graphs separately and perhaps the implementations for the combinatorial formulas from Lautizen's book. Perhaps also look into the formula for translating a mixed graph into an undirected graph.

**Comment by olgakuznetsova** [comment]
alright, I ran the example line-by-line without printing the output and it completes (at least till saturation).
Waiting for saturation now
