### ISSUE TITLE
Some inconsistency in the code.

### ISSUE THREAD

**Issue by harshitmotwani2015** [Macaulay2/Workshop-2020-Warwick#68]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/40596813ebf187c7bc2d5bb1c04479fff9340bb6/AlgebraicStatistics/MLE/StatGraphs.m2#L177

I think @roserhp has raised this issue earlier. I wanted to know if it should be g#graph#Graph or g#graph

**Comment by roserhp** [comment]
When they (in GraphicalModels for instance) use the function graph applied to a MixedGraph what they want is to transform the mixedGraph into a hashtable. So if we change this into g#graph#Graph a lot of things will break, since then what graph of a MixedGraph retrieves is the part of it that corresponds to undirected edges. I know the name of the function is totally misleading, but I think we shouldn't modify this...

**Comment by olgakuznetsova** [comment]
added Roser's comments in code (see referenced commit)
