### ISSUE TITLE
gaussianRings

### ISSUE THREAD

**Issue by roserhp** [Macaulay2/Workshop-2020-Warwick#95]
1. Should we have essentially one type of gaussianRing (i.e. gaussianRing of mixedGraphs) and then in the methods for graph and directed graph  just make a conversion of the graph to a mixedGraph?
Advantages: connected functions such as undirectedEdgesMatrix, covarianceMatrix, etc wouldn't need to have a multiple case scenario.

2. If we don't do the unification in 1., should we add gaussianRing bigraph (with the corresponding linked functions)?

3. Why do we check whether gaussianRingList already has content?
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/686475dc1b7d06ccbbd65c1601715931aa963ddc/AlgebraicStatistics/MLE/GraphicalModels.m2#L599
It seems to be the reason why we have issues dealing with different gaussianRings in the same M2 session, because it retrieves data already existing in the gaussianRingList hashtable.

4. Why is the gaussianRingData check needed?
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/686475dc1b7d06ccbbd65c1601715931aa963ddc/AlgebraicStatistics/MLE/GraphicalModels.m2#L702
Isn't it enough to check whether the ring comes from a suitable type of graph? 
(Obs: gaussianRingData cannot be accessed from outside GraphicalModels)

5. Last check of functions in GraphicalModels relying on gaussianRing. globalMarkov and similar only rely on graphs, but should we do something about it?

**Comment by olgakuznetsova** [comment]
@roserhp copying your email here to keep record
"My idea was the following:
- keep different rings for each type of graph (I think it would be to messy w.r.t. to the rest of functions in the package)
- homogenize gaussianRingData (for example, make sure that s variable is always in the same position such that we don't need to separate cases for computing covarianceMatrix)
- homogenize R.graph, R.mixedGraph, R.bigraph into R.graphType so that:
 
allows to check whether it's a gaussian ring coming from a graph (R.?gaussianRingData would no longer be necessary) 
g=R.graphType allows to recover the underlying graph of the right type without having to split into cases 

My first attempts weren't supersuccessful... For instance, covarianceMatrix is easy to simplify in this way but undirectedEdgesMatrix is more tricky because in the mixedGraph case we really need the partition here, so the contents gaussianRingData need to be carefully planned ahead. "

**Comment by olgakuznetsova** [comment]
@roserhp  Regarding gaussianRingData. How about we redefine it as a hash table everywhere? Then the value can be accessed by the keys that can be standard across all graphs and we won't need to worry about the position of an entry in the list.

(Or, if there is a risk that this will cause problems, we can just add gaussianRingDataHash where we convert gaussianRingData into a hash table and our functions can call gaussianRingDataHash and then just document this)

**Comment by roserhp** [comment]
In AlgebraicStatisticsRoser:

* R.gaussianRingData is now a hashtable that can be accessed from outside GraphicalModels. The possible keys are: nn (number of vertex), compU and compW (only applicable for mixedGraphs), sVar, kVar, lVar, pVar.
* R.graph, R.digraph and R.mixedGraph are now always R.graph no matter what the original type of graph was. In this way we can always access the graph with a single command and we avoid a great deal of if statements.
* A new attribute R.graphType is linked to the gaussianRing. It contains the class of the graph (Graph, Digraph and MixedGraph).

**Comment by olgakuznetsova** [comment]
Hi @roserhp, 

Could you help understand the following:

- gaussianRing and Bigraphs
`B=bigraph{{5,6},{6,7}}
gaussianRing B
`
I get
`QQ[k   , k   ,   k   , k   , k   , s   , s   , s   , s   , s   , s   ]
          5,5   6,6   7,7   5,6   6,7   5,5   5,6   5,7   6,6   6,7   7,7`
but I can't seem to find where it is computing it from in the code. 
Also, if I run 
`gaussianRing  mixedGraph B`
then I get
`QQ[p   , p   , p   , p   , p   , s   , s   , s   , s   , s   , s   ]
          5,5   6,6   7,7   5,6   6,7   5,5   5,6   5,7   6,6   6,7   7,7`  

When I run similar tests for Graphs (gaussianRing G and gaussianRing mixedGraph G) the rings coincide. However, if I try to do the same for Digraphs, the rings again are different.
`D=digraph{{1,6},{4,7}}`

Also, would it make sense to add a check isCyclic in the case of Digraph? It's done in a similar situation in pairMarkov and localMarkov

**Comment by roserhp** [comment]
As for the digraph case, as I said in #98, they are created in a weird way, only with the s variables. If Carlos and Luis agree I would do step 1 in #98. 
For the bigraph case, gaussianRing bigraphs doesn't exist. I've seen many times that functions that take graphs as input also allow bigraphs (I guess there's no conflict with the format since it's only pairs of vertices). This happens here again: that's why we have variables k (undirected edges) instead of p (bidirected). I suggest step 4 in #98.

**Comment by olgakuznetsova** [comment]
sounds good, thank you. I suspect Bigraph inherits the function for Graphs because Bigraph is a type of Graph.

Another thing I noted though: the order of the variables gets mixed up if I take mixedGraph (Bigraph)

`
B=bigraph{{5,6},{6,7}}
gaussianRing mixedGraph B
QQ[p   , p   , p   , p   , p   , s   , s   , s   , s   , s   , s   ]
          5,5   6,6   7,7   5,6   6,7   5,5   5,6   5,7   6,6   6,7   7,7
`
In particular, p_{7,7} is misplaced

**Comment by olgakuznetsova** [comment]
similarly, for gaussianRing mixedGraph Graph
`G=graph{{1,2},{1,3},{2,3}}`
` gaussianRing mixedGraph G`

QQ[k   , k   , k   , k   , k   , k   , s   , s   , s   , s   , s   , s   ]
          1,1   2,2   3,3   1,2   1,3   2,3   1,1   1,2   1,3   2,2   2,3   3,3

see k_{2,2} and k_{3,3}

**Comment by roserhp** [comment]
But this also happens if you do gaussianRing G (taking the input as a graph). Is this a problem? That's how gaussianRing graph was writen in the first place...first you get the elements in the diagonal and then the rest.

**Comment by olgakuznetsova** [comment]
ah ok, if this is intentional, then it's probably not a problem. I was just wondering if it is somehow related to the ordering bug we had earlier
