### ISSUE TITLE
directedEdgesMatrix for DAGs

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#98]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/f3b61c4b310f92c6cc27b3b115236b17ad0744c5/AlgebraicStatistics/MLE/GraphicalModels.m2#L763

Would it make sense to allow Digraphs here as well? Directed models are a valid type of model by itself and we even have a write-up on it in the MLEbackground (unlike Bigraphs for example).

**Comment by roserhp** [comment]
gaussianRings for digraphs is created in a weird way if you compare it to gaussianRings for graphs and mixedGraphs because it keeps very few data in gaussianRingData. This data would be necessary to build the directedEdgesMatrix. But if we allow the directedEdgesMatrix to take in digraphs, we should allow bidirectedEdgesMatrix to take digraphs as well, since the formula to compute covariance matrix for DAGs requires both Lambda and Omega (diagonal, but still necessary). Therefore, I think the natural way of doing all of this is via gaussianRing mixedGraphs. 

In the whole GraphicalModels code there is something specific for digraphs only once: in gaussianVanishingIdeal
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/f3b61c4b310f92c6cc27b3b115236b17ad0744c5/AlgebraicStatistics/MLE/GraphicalModels.m2#L975

but the piece of code for mixedGraphs would give the right answer as well.

My suggestion is the following:
1. Turn gaussianRing digraph into a function that calls gaussianRing mixedGraph for empty G and B.
2. Ask Luis if the computation of the gaussianRingIdeal for digraphs is more efficient than the one for mixedGraphs.
3. If the answer to 2 is yes, then we keep this if-statement checking when G and B are empty. If the answer is no, we remove this piece of code.
4. We can add gaussianRing bigraph doing something like in 1.

**Comment by olgakuznetsova** [comment]
Sounds reasonable, let's discuss on Wed

**Comment by roserhp** [comment]
done
